version: '3.4'

services:

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
  
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"

  cassandra:
    image: cassandra
    ports:
      - "9042:9042"
      